### PR TITLE
Split parsers and formatters

### PR DESCRIPTION
**Pull request by sebastiw**
Cleanup some gen servers and split the logic into component parts.

For instance there are now behaviours for both parsers as well as formatters.

I had to temporary remove support for expanded states, they are shown as a separate vertex in the graph.

It's quite the rewrite, sorry about that.

### CODE REVIEW

**Comment by lrascao** [comment]
thanks! i haven't touched in this project in like forever, i've sent you an invitation for collaboration, feel free add whatever you think is necessary. I can also transfer the project over to you if you so wish.

**Comment by sebastiw** [comment]
Thank you, is this published to hex automatically if I push a tag?

**Comment by lrascao** [comment]
> Thank you, is this published to hex automatically if I push a tag?

no, it's manual, i'll see about adding you to hex as well

**Comment by lrascao** [comment]
oof, can't seen to find where to add authors, do you remember?

**Comment by sebastiw** [comment]
I think you can do it with rebar3 [hex](https://hex.pm/docs/rebar3_publish) command, https://rebar3.org/docs/package_management/hex_package_management/
or possibly with a github action https://github.com/marketplace/actions/publish-to-hex

**Comment by lrascao** [comment]
alright, what email address can i use to add you as an owner?

**Comment by sebastiw** [comment]
***@***.*** is fine, thanks

**Comment by lrascao** [comment]
ah, github seems to be scrubbing emails in the comments, i only see asterisks

**Comment by sebastiw** [comment]
ah look at that!
it's visnae @ gmail, also found in git logs

**Comment by lrascao** [comment]
sorry for the lag, done now, thanks again!

**Pull request merged**
